[package]
name = "zerodeps-example"
version = "0.1.0"
edition = "2021"
publish = false

[dependencies]
merde = { path = "../merde", default-features = false }

[features]
default = []
merde = ["merde/core"]

